### ISSUE TITLE
Anschließende Monologe

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#1]
Szenen, die aus einem Monolog einer Figur bestehen, die von allen Figuren der vorherigen Szene verlassen werden, werden nicht erkannt da kein speaker-tag vorliegt. Beispiel bei Don Karlos 3.Akt/9. Auftritt oder weis_masaniello 1.Akt/21. Auftritt

**Comment by JohannaMeh** [comment]
kann nicht mehr bearbeitet werden
