### ISSUE TITLE
Date wird nicht gesetzt bei ca. 3 Dramen

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#11]
Beispiel: reut_femme_k, Grund: 
         <creation>
            <date/>
         </creation>
leeres date-tag also

**Comment by JohannaMeh** [comment]
Wenn keine Attribute im Date-Tag vorhanden sind, wird jetzt "unknown" als Wert für "when" gesetzt.
