### ISSUE TITLE
Datumsangabe ist selten richtig...

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#13]
... Manchmal steht für when das Publikationsdatum des Verlags, manchmal ist mit notbefore und notafter der Entstehungszeitraum gemeint, manchmal einfach das Geburts- und Sterbejahr des Autors, so gut wie nie das tatsächliche Erscheinungsjahr obwohl es bekannt ist.

**Comment by JohannaMeh** [comment]
kann leider nicht anhand der xml daten gelöst werden
