### ISSUE TITLE
Speakername manchmal mit newline verursacht Doppelung

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#14]
Beispiel: iff_verbrechen_k.xml

MADAME RUHLAND kommt meist als MADAMA RUHLAND manchmal als \nMADAME RUHLAND vor. Zwei unterschiedliche Speaker werden berechnet und die Datenlage wird vollständig verfälscht.

**Comment by JohannaMeh** [comment]
*RUHBERG
