### ISSUE TITLE
Leerer Speakertag

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#4]
Manchmal kommen leere Speakertags vor, Sinn ist mir noch nicht wirklich klar, Beispiel:
Hall liberata
Iffl figaro
Iffl jaeger
Kurz pumphia
Mitt soldat
Reut graf
weid_faust

**Comment by JohannaMeh** [comment]
hall_liberata, zeile 6636
