### ISSUE TITLE
Plötzliche Akte ohne Szenenangaben

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#5]
Drama entfernt sich von Akt-Szene-Struktur
Schlegel alarkos
tieck_verkehrtewelt
Tiek kater

Ähnlich, kein Akt aber Nachspiel oder ähnliches was nicht als act typisiert ist:
Neub schaeferfest

**Comment by JohannaMeh** [comment]
kann nicht mehr bearbeitet werden
