### ISSUE TITLE
<hi rend="italic"> nicht immer Bühnenanweisung

### ISSUE THREAD

**Issue by lauchblatt** [lauchblatt/QuantitativeDramenanalyseDH2015#6]
Beispiel: weis_lateiner 4.Akt/5. Auftritt 9.Replik
Statt Bühnenanweisung wohl nur stilistisches Mittel oder ähnliches

**Comment by JohannaMeh** [comment]
Nicht lösbar, weil es in anderen Stücken genauso auch verwendet wird, es da aber eine Bühnenanweisung ist, die ignoriert werden soll. Und es gibt keinen Unterschied zwischen den Verwendungen von <hi rend="italic">.

**Comment by JohannaMeh** [comment]
Die Bühnenanweisungen überwiegen zahlenmäßig und auch an Wörtern, sie werden weiterhin aussortiert.
